Avoid hitting `unused_attributes` warning for `automatically_derived`.
On latest nightly of `rustc`, errors like the one below would happen
when running `cargo test`:

```
error: `#[automatically_derived]` only has an effect on trait implementation blocks
  --> tests/ffi/module.rs:40:12
   |
40 |         fn c_take_trivial_ref_method(self: &D);
   |            ^^^^^^^^^^^^^^^^^^^^^^^^^
   |
note: the lint level is defined here
  --> tests/ffi/module.rs:1:9
   |
1  | #![deny(warnings)] // Check that expansion of `cxx::bridge` doesn't trigger warnings.
   |         ^^^^^^^^
   = note: `#[deny(unused_attributes)]` implied by `#[deny(warnings)]`
```

This commit adds `#[allow(unused_attributes)]` above each place that
emits `#[automatically_derived]`.  This is sufficient to keep CI
and `cargo test` clean of warnings/errors.

FWIW emitting the `#[automatically_derived]` attribute was added in
https://github.com/dtolnay/cxx/commit/1d4fe980351f015d9ef39f9d9ed360495f72aa71